LAB2_ASP/Models/Birth.cs
using static LAB2_SIWON.Controllers.CalculatorController;

namespace LAB2_SIWON.Models
{
    public class Birth
    {
        public string? X { get; set; }
        public DateTime? Y { get; set; }




        public bool IsValid()
        {
            return  X != null && Y != null && Y<=DateTime.Today;
        }


        public int BirthCalculate()
        {
            

            // Obliczanie wieku na podstawie daty urodzenia
            var today = DateTime.Today;
            var age = today.Year - Y.Value.Year;

            // Jeśli data urodzin jeszcze nie miała miejsca w bieżącym roku, odejmij 1 rok
            //if (Y.Value.Date > today.AddYears(-age)) age--;

            return age;

        }
    }
}

LAB2_ASP/Models/Calculator.cs
using static LAB2_SIWON.Controllers.CalculatorController;

namespace LAB2_SIWON.Models
{
    public class Calculator
    {
        public enum Operators
        {
            Unknown, Add, Mul, Sub, Div
        }
        public Operators? Operator { get; set; }
        public double? X { get; set; }
        public double? Y { get; set; }

        public String Op
        {
            get
            {
                switch (Operator)
                {
                    case Operators.Add:
                        return "+";

                    case Operators.Div:
                        return "/";

                    case Operators.Mul:
                        return "*";

                    case Operators.Sub:
                        return "-";

                    default:
                        return "";
                }
            }
        }

        public bool IsValid()
        {
            return Operator != null && X != null && Y != null;
        }

        public double Calculate()
        {
            switch (Operator)
            {
                case Operators.Add:
                    return (double)(X + Y);

                case Operators.Mul:
                    return (double)(X * Y);

                case Operators.Sub:
                    return (double)(X - Y);

                case Operators.Div:
                    if (Y != 0)
                        return (double)(X / Y);
                    else
                        throw new DivideByZeroException();

                default: return double.NaN;
            }
        }
    }
}

LAB2_ASP/Models/ErrorViewModel.cs
namespace LAB2_SIWON.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LAB2_ASP/Controllers/BirthController.cs
using LAB2_SIWON.Models;
using Microsoft.AspNetCore.Mvc;

namespace LAB2_SIWON.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result([FromForm] Birth model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }

            //double wynik = model.Calculate();  
            // ViewBag.Result = wynik;  
            return View(model);
        }
    }
}

LAB2_ASP/Controllers/CalculatorController.cs
using LAB2_SIWON.Models;
using Microsoft.AspNetCore.Mvc;

namespace LAB2_SIWON.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        ///Calculator/Result?x=2&operator=add&y=3

        public IActionResult Form()
        {
            return View();
        }
        public enum Operator
        {
            Unknown, Add, Mul, Sub, Div
        }

        // PO STWORZENIU MODELU
        //W metodzie wskazano, które dane żądania powinny utworzyć model.
        //Atrybut [FromForm] wskazuje, że model
        //typu Calculator powinien zostać utworzony na podstawie
        //ciała żądania, w którym są dane z formularza
        [HttpPost]
        public IActionResult Result([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }

            //double wynik = model.Calculate();  
           // ViewBag.Result = wynik;  
            return View(model);
        }
        //PRZED UZYCIEM MODELU
        /*
        public IActionResult Result(Operator op, double? a, double? b)
        {
            double? result = null;

            if (a.HasValue && b.HasValue)
            {
                switch (op)
                {
                    case Operator.Add:
                        result = a + b;
                        break;
                    case Operator.Sub:
                        result = a - b;
                        break;
                    case Operator.Mul:
                        result = a * b;
                        break;
                    case Operator.Div:
                        if (b != 0)
                            result = a / b;
                        break;
                    default:
                        ViewBag.ErrorMessage = "Nieznany operator";
                        break;
                }
            }

            ViewBag.Op = op;
            ViewBag.a = a;
            ViewBag.b = b;
            ViewBag.Result = result;

            return View();

        }
        */
    }
}

LAB2_ASP/Controllers/HomeController.cs
using LAB2_SIWON.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LAB2_SIWON.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LAB2_ASP/Views/Birth/Form.cshtml
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Formularz Urodzinowy</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="X">Imię</label>
                    <input class="form-control" type="text" name="X" id="x" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="Y">Data</label>
                    <input class="form-control" type="date" name="Y" id="y" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

LAB2_ASP/Views/Birth/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>@Model.X  @Model.Y=</H3>
<p>Cześć @Model.X, masz @Model.BirthCalculate() lat(a).</p>

LAB2_ASP/Views/Calculator/Form.cshtml
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            action="Result" oznacza, że po kliknięciu "Oblicz", formularz wyśle dane do metody akcji o nazwie Result w kontrolerze.
            method="POST" oznacza, że te dane zostaną wysłane jako żądanie POST (jest to standardowy sposób wysyłania danych z formularza).
            Formularz kalkulatora wysyła żądania typu GET, co powoduje, że dane formularza są dołączane jako query do url żądania. Są jednak sytuacje, gdy wysyłanie danych w query nie jest wskazane, np. dane logowania. Osoba stojąca obok mogłaby zobaczyć wrażliwe dane wyświetlane w pasku adresu przeglądarki.

            Zmienimy typ metody formularza na POST, co spowoduje, że dane formularza zostaną przesłane w ciele żądania.
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="X">Liczba 1</label>
                    <input class="form-control" type="number" name="X" step="0.00001" id="x" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="op">Operator</label>
                    
                    <select name="operator">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="Y">Liczba 2</label>
                    <input class="form-control" type="number" name="Y" step="0.00001" id="y" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

LAB2_ASP/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X @Model.Op @Model.Y=</H3>
<h3>@Model.Calculate()</h3>

LAB2_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LAB2_SIWON</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LAB2_SIWON.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LAB2_SIWON</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Calculator" asp-action="Form">Kalkulator</a> <!-- Link do formularza -->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Birth" asp-action="Form">BirthCalculator</a> <!-- Link do formularza -->
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LAB2_SIWON - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>